import { describe, expect, test } from "bun:test";
import {
  linkInputSchema,
  linkUpdateSchema,
  ruleInput,
  slugSchema,
  toCreateLinkCommand,
  toUpdateLinkCommand,
} from "./schemas";

describe("slugSchema", () => {
  test("accepts lowercase + digits + hyphens", () => {
    expect(() => slugSchema.parse("intro-30min")).not.toThrow();
    expect(() => slugSchema.parse("a")).not.toThrow();
  });
  test("rejects uppercase / spaces / unicode", () => {
    expect(() => slugSchema.parse("Intro")).toThrow();
    expect(() => slugSchema.parse("intro 30")).toThrow();
    expect(() => slugSchema.parse("インタビュー")).toThrow();
  });
  test("rejects too long", () => {
    expect(() => slugSchema.parse("a".repeat(65))).toThrow();
  });
});

describe("ruleInput", () => {
  test("accepts a valid weekday window", () => {
    expect(() => ruleInput.parse({ weekday: 1, startMinute: 540, endMinute: 1020 })).not.toThrow();
  });
  test("rejects start >= end", () => {
    expect(() => ruleInput.parse({ weekday: 1, startMinute: 540, endMinute: 540 })).toThrow();
    expect(() => ruleInput.parse({ weekday: 1, startMinute: 600, endMinute: 540 })).toThrow();
  });
  test("rejects out-of-range weekday", () => {
    expect(() => ruleInput.parse({ weekday: 7, startMinute: 0, endMinute: 60 })).toThrow();
  });
  test("accepts endMinute === 24*60", () => {
    expect(() => ruleInput.parse({ weekday: 1, startMinute: 0, endMinute: 1440 })).not.toThrow();
  });
});

describe("linkInputSchema", () => {
  const minimal = {
    slug: "intro",
    title: "Intro",
    durationMinutes: 30,
    timeZone: "Asia/Tokyo",
  };

  test("applies defaults", () => {
    const parsed = linkInputSchema.parse(minimal);
    expect(parsed.rangeDays).toBe(60);
    expect(parsed.rules).toEqual([]);
  });

  test("rejects invalid duration", () => {
    expect(() => linkInputSchema.parse({ ...minimal, durationMinutes: 0 })).toThrow();
    expect(() => linkInputSchema.parse({ ...minimal, durationMinutes: -10 })).toThrow();
  });

  test("accepts valid full payload", () => {
    expect(() =>
      linkInputSchema.parse({
        ...minimal,
        description: "30 min meeting",
        rangeDays: 30,
        rules: [
          { weekday: 1, startMinute: 540, endMinute: 720 },
          { weekday: 1, startMinute: 780, endMinute: 1020 },
        ],
      }),
    ).not.toThrow();
  });

  // ISH-296 (B): slug は optional になり、未指定でも parse できる
  test("slug omitted is accepted (auto-generated by usecase)", () => {
    const { slug: _omit, ...noSlug } = minimal;
    void _omit;
    const parsed = linkInputSchema.parse(noSlug);
    expect(parsed.slug).toBeUndefined();
  });
});

describe("linkUpdateSchema", () => {
  test("allows partial input", () => {
    expect(() => linkUpdateSchema.parse({ title: "new" })).not.toThrow();
    expect(() => linkUpdateSchema.parse({ rules: [] })).not.toThrow();
    expect(() => linkUpdateSchema.parse({})).not.toThrow();
  });
});

describe("toCreateLinkCommand", () => {
  const baseWire = linkInputSchema.parse({
    slug: "intro",
    title: "Intro",
    durationMinutes: 30,
    timeZone: "Asia/Tokyo",
  });

  test("normalizes nullable+optional description to null", () => {
    // Omitting description → undefined on the wire shape, but the command
    // should always have null so the repo never has to deal with `undefined`
    // for the nullable column.
    const cmd = toCreateLinkCommand(baseWire);
    expect(cmd.description).toBeNull();
  });

  test("preserves explicit nulls", () => {
    const cmd = toCreateLinkCommand({
      ...baseWire,
      description: null,
    });
    expect(cmd.description).toBeNull();
  });

  test("forwards all defaulted scalar fields", () => {
    const cmd = toCreateLinkCommand(baseWire);
    expect(cmd.rangeDays).toBe(60);
    expect(cmd.rules).toEqual([]);
  });

  // ISH-296 (B): slug が undefined のまま渡れば command でも省略される
  test("slug undefined remains absent on the command (usecase will generate)", () => {
    const wire = linkInputSchema.parse({
      title: "Intro",
      durationMinutes: 30,
      timeZone: "Asia/Tokyo",
    });
    const cmd = toCreateLinkCommand(wire);
    expect("slug" in cmd).toBe(false);
  });
});

describe("toUpdateLinkCommand", () => {
  // NOTE: `linkUpdateSchema = linkInputSchema.partial()` keeps the inner
  // `.default(...)` annotations, so Zod still fills defaults for fields like
  // `rangeDays` even when the user omitted them in PATCH. The mapper forwards
  // every key whose value is not `undefined`, so those defaults flow through.
  // This is the existing PATCH behaviour (unchanged by ISH-124 / ISH-298) —
  // the tests below pin it so any future change is intentional.

  test("only-default fields are filled by Zod and forwarded", () => {
    const cmd = toUpdateLinkCommand(linkUpdateSchema.parse({}));
    expect(cmd).toEqual({
      rangeDays: 60,
      rules: [],
    });
  });

  test("user-supplied keys override Zod defaults", () => {
    const cmd = toUpdateLinkCommand(linkUpdateSchema.parse({ title: "renamed" }));
    expect(cmd.title).toBe("renamed");
  });

  test("explicit null on description is preserved (vs missing key)", () => {
    const cmd = toUpdateLinkCommand(linkUpdateSchema.parse({ description: null }));
    expect("description" in cmd).toBe(true);
    expect(cmd.description).toBeNull();
  });

  // Pin the mapper's narrow contract independently of Zod's parse step:
  // given a literal input with truly missing keys, the output must also be
  // missing those keys (not `undefined`). This is what `repo.linkColumnsForUpsert`
  // relies on to leave columns alone.
  test("genuinely missing keys do not appear in the output (post-Zod contract)", () => {
    const cmd = toUpdateLinkCommand({ title: "renamed" });
    expect("rangeDays" in cmd).toBe(false);
  });
});
