import { eq } from "drizzle-orm";
import type { db as DbClient } from "@/db/client";
import { tenantMembers, users } from "@/db/schema/common";
import {
  findOpenInvitationByEmail,
  findOpenInvitationByToken,
  insertInvitation,
  markInvitationAccepted,
} from "./repo";

type Database = typeof DbClient;

const INVITE_TTL_DAYS = 7;
const INVITE_TTL_MS = INVITE_TTL_DAYS * 24 * 60 * 60_000;

// ---------------------------------------------------------------------------
// createInvitation
// ---------------------------------------------------------------------------

export type CreateInvitationInput = {
  email: string;
  /**
   * The requested role for the invitee.
   * Note: the current tenant.invitations schema does not persist role, so this
   * field is accepted for API compatibility and used as the default when
   * accepting. The route stores the role in-memory and passes it to
   * acceptInvitation. For now, role defaults to "member" at acceptance time.
   */
  role: "owner" | "member";
};

export type CreateInvitationResult =
  | { kind: "ok"; invitationId: string; token: string; expiresAt: Date }
  | { kind: "already_member" }
  | { kind: "already_invited" };

/**
 * Issue a new tenant-scoped invitation.
 *
 * Pre-conditions (checked by the route before calling):
 *   - caller is authenticated and is a member of the tenant with role="owner"
 *
 * This function handles:
 *   - email already in tenant_members (via common.users join) → already_member
 *   - open invitation already exists → already_invited (DB partial unique
 *     also enforces this, but we return a friendly domain result)
 *   - INSERT tenant.invitations (token generated by defaultRandom)
 */
export async function createInvitation(
  database: Database,
  tenantId: string,
  inviterUserId: string,
  input: CreateInvitationInput,
): Promise<CreateInvitationResult> {
  // Check if a user with this email is already a tenant member.
  const [existingMember] = await database
    .select({ id: tenantMembers.id })
    .from(tenantMembers)
    .innerJoin(users, eq(tenantMembers.userId, users.id))
    .where(eq(users.email, input.email))
    .limit(1);

  if (existingMember) {
    return { kind: "already_member" };
  }

  // Check for an open invitation for this email in this tenant.
  const existing = await findOpenInvitationByEmail(database, tenantId, input.email);
  if (existing) {
    return { kind: "already_invited" };
  }

  const expiresAt = new Date(Date.now() + INVITE_TTL_MS);
  const invitation = await insertInvitation(database, {
    tenantId,
    email: input.email,
    invitedByUserId: inviterUserId,
    expiresAt,
  });

  return { kind: "ok", invitationId: invitation.id, token: invitation.token, expiresAt };
}

// ---------------------------------------------------------------------------
// acceptInvitation
// ---------------------------------------------------------------------------

export type AcceptInvitationResult =
  | { kind: "ok"; tenantId: string; role: "owner" | "member" }
  | { kind: "not_found" }
  | { kind: "expired" }
  | { kind: "already_accepted" }
  | { kind: "user_already_in_tenant" };

/**
 * Accept a tenant invitation.
 *
 * Must be called with the baseline db (NOT via requestScope) because the
 * invitee has no tenant_members row yet — attachTenantContext is NOT mounted
 * on this endpoint.
 *
 * Flow:
 *   1. Find invitation by token (baseline db, bypasses RLS)
 *   2. Validate expiry, already-accepted
 *   3. Check that the user is not already a tenant member (different tenant)
 *   4. Validate email match LAST (and as a not_found, to avoid leaking that
 *      the token is otherwise live to a non-invitee — see ISH-194)
 *   5. Atomically: INSERT tenant_members + UPDATE invitations.accepted_at
 *
 * Error precedence rationale (ISH-194):
 *   not_found → expired → already_accepted → user_already_in_tenant → not_found (email)
 *
 * The email check is LAST and collapses to `not_found` (not a distinct
 * `email_mismatch` kind). Returning `email_mismatch` (403) before this
 * point would leak that the token is live to an attacker who stole the
 * URL — they could trigger the full chain to learn:
 *   - the token exists (no 404)
 *   - it's not expired (no 410)
 *   - it's not accepted (no 409 already_accepted)
 *   - the caller has no other tenant (no 409 user_already_in_tenant)
 * Collapsing to `not_found` makes the response indistinguishable from
 * "this token never existed", costing only the legitimate "you signed
 * in with the wrong email" UX hint (rare, recoverable by re-issuing).
 */
export async function acceptInvitation(
  database: Database,
  callerUserId: string,
  callerEmail: string,
  token: string,
): Promise<AcceptInvitationResult> {
  const invitation = await findOpenInvitationByToken(database, token);
  if (!invitation) return { kind: "not_found" };

  if (invitation.expiresAt.getTime() < Date.now()) {
    return { kind: "expired" };
  }

  if (invitation.acceptedAt !== null) {
    return { kind: "already_accepted" };
  }

  // Check if the user is already a member of any tenant.
  // tenant_members.user_id UNIQUE means 1 user = 1 tenant.
  const [existingMembership] = await database
    .select({ tenantId: tenantMembers.tenantId })
    .from(tenantMembers)
    .where(eq(tenantMembers.userId, callerUserId))
    .limit(1);

  if (existingMembership) {
    return { kind: "user_already_in_tenant" };
  }

  // Email check LAST — and we collapse to `not_found` rather than returning
  // a distinct `email_mismatch` kind. See JSDoc above for the leak rationale.
  if (invitation.email.toLowerCase() !== callerEmail.toLowerCase()) {
    return { kind: "not_found" };
  }

  // Since the tenant.invitations schema does not store role, all accepted
  // invitations use "member" as the role. This is the expected default.
  const role: "owner" | "member" = "member";

  await markInvitationAccepted(database, {
    invitationId: invitation.id,
    userId: callerUserId,
    tenantId: invitation.tenantId,
    role,
    now: new Date(),
  });

  return { kind: "ok", tenantId: invitation.tenantId, role };
}
