import { eq } from "drizzle-orm";
import type { db as DbClient } from "@/db/client";
import { type TenantMemberRole, tenantMembers, users } from "@/db/schema/common";
import { workspaceInviteEmail } from "@/notifications/templates";
import type { SendEmailFn } from "@/notifications/types";
import {
  deleteInvitationForTenant,
  findInvitationByIdForTenant as findInvitationLookupForTenant,
} from "@/tenant-members/repo";
import { findWorkspaceById } from "@/workspaces/repo";
import {
  findInvitationByIdForTenant,
  findOpenInvitationByEmail,
  findOpenInvitationByToken,
  insertInvitation,
  markInvitationAccepted,
  updateInvitationExpiry,
} from "./repo";

type Database = typeof DbClient;

const INVITE_TTL_DAYS = 7;
const INVITE_TTL_MS = INVITE_TTL_DAYS * 24 * 60 * 60_000;

// ---------------------------------------------------------------------------
// createInvitation
// ---------------------------------------------------------------------------

export type CreateInvitationInput = {
  email: string;
  /**
   * The requested role for the invitee. Persisted on tenant.invitations.role
   * (ISH-252) and read back when the invitation is accepted, so an "owner"
   * invite actually creates an owner tenant_members row.
   */
  role: TenantMemberRole;
};

export type CreateInvitationResult =
  | { kind: "ok"; invitationId: string; token: string; expiresAt: Date }
  | { kind: "already_member" }
  | { kind: "already_invited" };

/**
 * Issue a new tenant-scoped invitation.
 *
 * Pre-conditions (checked by the route before calling):
 *   - caller is authenticated and is a member of the tenant with role="owner"
 *
 * This function handles:
 *   - email already in tenant_members (via common.users join) → already_member
 *   - open invitation already exists → already_invited (DB partial unique
 *     also enforces this, but we return a friendly domain result)
 *   - INSERT tenant.invitations (token generated by defaultRandom)
 */
export async function createInvitation(
  database: Database,
  tenantId: string,
  inviterUserId: string,
  input: CreateInvitationInput,
): Promise<CreateInvitationResult> {
  // ISH-195: normalize email to lowercase BEFORE every read/write so the
  // uniqueness checks, the partial unique index `uniq_tenant_email_open`,
  // and the future acceptance comparison all see one canonical form.
  // Previously: `Bob@x.com` invite + `bob@x.com` sign-up bypassed the
  // already_invited / already_member checks because they string-compared
  // the raw values.
  const email = input.email.toLowerCase();

  // Check if a user with this email is already a tenant member.
  const [existingMember] = await database
    .select({ id: tenantMembers.id })
    .from(tenantMembers)
    .innerJoin(users, eq(tenantMembers.userId, users.id))
    .where(eq(users.email, email))
    .limit(1);

  if (existingMember) {
    return { kind: "already_member" };
  }

  // Check for an open invitation for this email in this tenant.
  const existing = await findOpenInvitationByEmail(database, tenantId, email);
  if (existing) {
    return { kind: "already_invited" };
  }

  const expiresAt = new Date(Date.now() + INVITE_TTL_MS);
  const invitation = await insertInvitation(database, {
    tenantId,
    email,
    invitedByUserId: inviterUserId,
    expiresAt,
    role: input.role,
  });

  return { kind: "ok", invitationId: invitation.id, token: invitation.token, expiresAt };
}

// ---------------------------------------------------------------------------
// acceptInvitation
// ---------------------------------------------------------------------------

export type AcceptInvitationResult =
  | { kind: "ok"; tenantId: string; role: TenantMemberRole }
  | { kind: "not_found" }
  | { kind: "expired" }
  | { kind: "already_accepted" }
  | { kind: "user_already_in_tenant" };

/**
 * Accept a tenant invitation.
 *
 * Must be called with the baseline db (NOT via requestScope) because the
 * invitee has no tenant_members row yet — attachTenantContext is NOT mounted
 * on this endpoint.
 *
 * Flow:
 *   1. Find invitation by token (baseline db, bypasses RLS)
 *   2. Validate expiry, already-accepted
 *   3. Check that the user is not already a tenant member (different tenant)
 *   4. Validate email match LAST (and as a not_found, to avoid leaking that
 *      the token is otherwise live to a non-invitee — see ISH-194)
 *   5. Atomically: INSERT tenant_members + UPDATE invitations.accepted_at
 *
 * Error precedence rationale (ISH-194):
 *   not_found → expired → already_accepted → user_already_in_tenant → not_found (email)
 *
 * The email check is LAST and collapses to `not_found` (not a distinct
 * `email_mismatch` kind). Returning `email_mismatch` (403) before this
 * point would leak that the token is live to an attacker who stole the
 * URL — they could trigger the full chain to learn:
 *   - the token exists (no 404)
 *   - it's not expired (no 410)
 *   - it's not accepted (no 409 already_accepted)
 *   - the caller has no other tenant (no 409 user_already_in_tenant)
 * Collapsing to `not_found` makes the response indistinguishable from
 * "this token never existed", costing only the legitimate "you signed
 * in with the wrong email" UX hint (rare, recoverable by re-issuing).
 */
export async function acceptInvitation(
  database: Database,
  callerUserId: string,
  callerEmail: string,
  token: string,
): Promise<AcceptInvitationResult> {
  const invitation = await findOpenInvitationByToken(database, token);
  if (!invitation) return { kind: "not_found" };

  if (invitation.expiresAt.getTime() < Date.now()) {
    return { kind: "expired" };
  }

  if (invitation.acceptedAt !== null) {
    return { kind: "already_accepted" };
  }

  // Check if the user is already a member of any tenant.
  // tenant_members.user_id UNIQUE means 1 user = 1 tenant.
  const [existingMembership] = await database
    .select({ tenantId: tenantMembers.tenantId })
    .from(tenantMembers)
    .where(eq(tenantMembers.userId, callerUserId))
    .limit(1);

  if (existingMembership) {
    return { kind: "user_already_in_tenant" };
  }

  // Email check LAST — and we collapse to `not_found` rather than returning
  // a distinct `email_mismatch` kind. See JSDoc above for the leak rationale.
  if (invitation.email.toLowerCase() !== callerEmail.toLowerCase()) {
    return { kind: "not_found" };
  }

  // ISH-252: read the persisted role from the invitation row. The DB-level
  // CHECK constraint matches TENANT_MEMBER_ROLES (and the column has a
  // default of 'member'), so this cast is safe.
  const role = invitation.role as TenantMemberRole;

  await markInvitationAccepted(database, {
    invitationId: invitation.id,
    userId: callerUserId,
    tenantId: invitation.tenantId,
    role,
    now: new Date(),
  });

  return { kind: "ok", tenantId: invitation.tenantId, role };
}

// ---------------------------------------------------------------------------
// revokeTenantInvitation (ISH-256)
// ---------------------------------------------------------------------------

/**
 * Revoke (delete) a still-open tenant invitation. Caller authorization
 * (owner-only) is enforced at the route layer via `getTenantRole(c)`. Once
 * accepted, the invitation row is kept for audit and cannot be deleted via
 * this endpoint.
 *
 * Status precedence:
 *   not_found → already_accepted → ok
 */
export type RevokeTenantInvitationResult =
  | { kind: "ok" }
  | { kind: "not_found" }
  | { kind: "already_accepted" };

export async function revokeTenantInvitation(
  database: Database,
  _callerUserId: string,
  tenantId: string,
  invitationId: string,
): Promise<RevokeTenantInvitationResult> {
  const invitation = await findInvitationLookupForTenant(database, tenantId, invitationId);
  if (!invitation) return { kind: "not_found" };
  if (invitation.acceptedAt !== null) return { kind: "already_accepted" };

  const deleted = await deleteInvitationForTenant(database, tenantId, invitationId);
  if (!deleted) return { kind: "not_found" };
  return { kind: "ok" };
}

// ---------------------------------------------------------------------------
// resendTenantInvitation (ISH-261)
// ---------------------------------------------------------------------------

/**
 * ISH-261: resend a still-open tenant invitation, extending its expiry by
 * `INVITE_TTL_MS` (24h per ticket spec — overrides the original 7d TTL so
 * the recipient gets a fresh window from the moment of resend).
 *
 * Caller authorization (owner-only) is enforced at the route layer via
 * `getTenantRole(c) === 'owner'`.
 *
 * Status precedence:
 *   not_found → already_accepted → ok
 *
 * Email delivery is best-effort (mirrors `issueInvitation`): the row's
 * `expiresAt` is committed before send, and a delivery failure is logged but
 * does NOT roll back the extension. The operator can always click 再送 again.
 */
export type ResendTenantInvitationDeps = {
  sendEmail: SendEmailFn;
  appBaseUrl: string;
  /** override-able for tests; defaults to Date.now() */
  now?: () => number;
};

export type ResendTenantInvitationResult =
  | { kind: "ok"; invitationId: string; expiresAt: Date }
  | { kind: "not_found" }
  | { kind: "already_accepted" };

const RESEND_TTL_MS = 24 * 60 * 60_000; // 24h per ticket spec

export async function resendTenantInvitation(
  database: Database,
  tenantId: string,
  invitationId: string,
  deps: ResendTenantInvitationDeps,
): Promise<ResendTenantInvitationResult> {
  const invitation = await findInvitationByIdForTenant(database, tenantId, invitationId);
  if (!invitation) return { kind: "not_found" };
  if (invitation.acceptedAt !== null) return { kind: "already_accepted" };

  const now = deps.now?.() ?? Date.now();
  const expiresAt = new Date(now + RESEND_TTL_MS);
  const updated = await updateInvitationExpiry(database, invitation.id, expiresAt);
  // Row vanished between read and write (canceled in another tab) — collapse
  // to not_found so the FE re-fetches the listing.
  if (!updated) return { kind: "not_found" };

  // Best-effort email — mirrors issueInvitation's policy. The row is already
  // committed, so a delivery failure is logged + swallowed.
  try {
    const workspace = await findWorkspaceById(database, tenantId);
    await deps.sendEmail(
      workspaceInviteEmail({
        to: invitation.email,
        workspaceName: workspace?.name ?? "ワークスペース",
        acceptUrl: `${deps.appBaseUrl}/invite/${invitation.token}`,
        expiresAt,
      }),
    );
  } catch (err) {
    console.warn("[invite] failed to resend invitation email; row kept:", err);
  }

  return { kind: "ok", invitationId: invitation.id, expiresAt };
}
